name: Simple Workflow 2

on:
  push:          # Запуск при пуше в любую ветку
  pull_request:  # Запуск при создании или обновлении Pull Request

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Greet the user
        run: echo "Hello, ${{ github.actor }}! This is a simple GitHub Actions workflow."

      - name: Indicate success
        run: echo "✅ The workflow has completed successfully!"
